dictionaries = ["en_us", "en_gb"]

words = [
    "codebook",
    "pyright",
    "urlpatterns",
    "fbsurvivor",
    "endfor",
    "venmo",
    "templatetags",
    "runserver",
    "venv",
    "playerstatus",
    "playerstatuses",
    "queryset",
    "favicons",
    "mstile",
]

ignore_paths = [
    "**/settings.py",
    "**/pyproject.toml",
    "**/*.json",
    "**/*.toml"
]
