dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "codebook",
    "endfor",
    "favicons",
    "fbsurvivor",
    "justfile",
    "leaderboard",
    "makemigrations",
    "mstile",
    "passwordless",
    "playerstatus",
    "playerstatuses",
    "psycopg",
    "pyproject",
    "pyrefly",
    "pyright",
    "queryset",
    "querysets",
    "runserver",
    "showmigrations",
    "templatetags",
    "urlpatterns",
    "venmo",
    "venv",
]
ignore_paths = [
    "**/settings.py",
    "**/pyproject.toml",
    "**/*.json",
    "**/*.toml",
]
